[sources.sql_database.credentials]
drivername = "postgresql"
host       = "your-postgres-host"
port       = 5432
username   = "your-username"
password   = "your-password"
database   = "your-database"

[destination.redshift.credentials]
drivername = "redshift+psycopg2"
host       = "your-redshift-host"
port       = 5439
username   = "your-redshift-username"
password   = "your-redshift-password"
database   = "your-redshift-database"
