[sources.sql_database.credentials]
drivername = "postgresql"
host       = "your-postgres-host"
port       = 5432
username   = "your-username"
password   = "your-password"
database   = "your-database"

[destination.postgres.credentials]
drivername = "postgresql"
host       = "your-postgres-host"
port       = 5432
username   = "your-username"
password   = "your-password"
database   = "your-database"
